### ISSUE TITLE
Code's maintenance

### ISSUE THREAD

**Issue by tz70s** [allenlee820202/nexcom-project#17]
We should speed up this progress, add the standalone issue for tracking.
Mostly accomplished, but still lacks of lots of **comments**.
IMHO, the comments are **NOT** necessarily written liked `checker.js` as a **TUTORIAL STYLE**,
Describe the functionality and the argument or anything else simply is fine. I think the code is clear enough.

**Comment by tz70s** [comment]
I think it's clear enough currently, close this out! Thanks!

**Comment by allenlee820202** [comment]
Thanks for the review!
